Metrics/ClassLength:
  Description: 'Avoid classes longer than 100 lines of code.'
  Max: 165

Metrics/LineLength:
  Description: 'Limit lines to 80 characters.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#80-character-limits'
  Enabled: true
  Max: 250
  Exclude:
    - site-cookbooks/b_kibana/spec/configure_service_spec.rb

Metrics/MethodLength:
  Description: 'Avoid methods longer than 10 lines of code.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#short-methods'
  Enabled: true
  Max: 15

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/FileName:
  Description: 'Use snake_case for source file names.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#snake-case-files'
  Enabled: true
  Exclude:
    - lib/aws-cache.rb
