language: ruby
rvm:
- 1.9.3
cache:
- bundler
script: bundle exec rspec spec
deploy:
  provider: rubygems
  api_key:
    secure: qTdziX+VEf9OQzamyQcvsC+8hSrtnjMxDpLkSABcI8HyJAcPcvCPCRQot8sE+5xLVYf8owWitXWhl6NCC5FudyzjwU9GeqhK/GRKVO0MNJcE1OvjxyYVogIipyQT4M1qItuuBmU+dceUwDFLqWM1K/hsLZCm1NHR+u0EktnsQDM=
