language: ruby
rvm:
  - 2.0.0
  - 2.2.3
sudo: false
cache: bundler
script: bundle exec rake
deploy:
  provider: rubygems
  api_key:
    secure: qTdziX+VEf9OQzamyQcvsC+8hSrtnjMxDpLkSABcI8HyJAcPcvCPCRQot8sE+5xLVYf8owWitXWhl6NCC5FudyzjwU9GeqhK/GRKVO0MNJcE1OvjxyYVogIipyQT4M1qItuuBmU+dceUwDFLqWM1K/hsLZCm1NHR+u0EktnsQDM=
